---

port: 4444
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: pacific
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
#title:       "SinglePaged - Simple Jekyll template"
title:       "Scientific Transparency"
keywords:    "SDM, nims, scitran"
description: "Scientific Transparency"
source_link: "https://github.com/scitran"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#00a4e0'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#f7941e'
  turquoise: '#0fbfcf'
